json.patient_identifier participant.patient_identifier
json.guid participant.guid
json.clinic participant.clinic
json.health_worker_guid participant.health_worker.guid
json.research_assistant_guid participant.research_assistant.guid